### ISSUE TITLE
unable to run stationary-test.py

### ISSUE THREAD

**Issue by akram1335** [twitu/sdn-vanet#6]
`sudo python3 stationary-test.py
*** Creating nodes
*** Configuring wifi nodes
*** Connecting to wmediumd server /var/run/wmediumd.sock
*** Creating links
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "stationary-test.py", line 59, in run
    net.addLink(self.stations[0], cls=adhoc, ssid='adhocNet', mode='g', channel=5)
  File "/usr/local/lib/python3.8/dist-packages/mininet_wifi-2.5-py3.8.egg/mn_wifi/net.py", line 600, in addLink
    link = cls(node=node1, **params)
TypeError: __init__() missing 1 required positional argument: 'intf'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "stationary-test.py", line 90, in run
    shared_mem = SharedMemory(6789, flags=sysv_ipc.IPC_CREAT, size=sysv_ipc.PAGE_SIZE, init_character='\0')
TypeError: argument 5 must be a byte string of length 1, not str
`

**Comment by rushanthan03** [comment]
how can i handle this error
